// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package testclient

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"go.infratographer.com/x/gidx"
)

// An object with an ID.
// Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
type Node interface {
	IsNode()
	// The id of the object.
	GetID() gidx.PrefixedID
}

type Entity interface {
	IsEntity()
}

// Create a new ResourceProvider.
type CreateResourceProviderInput struct {
	// The name of the resource provider.
	Name string `json:"name"`
	// The description of the resource provider.
	Description *string `json:"description,omitempty"`
	// The ID for the owner for this resource provider.
	OwnerID gidx.PrefixedID `json:"ownerID"`
}

type Owner struct {
	ID               gidx.PrefixedID            `json:"id"`
	ResourceProvider ResourceProviderConnection `json:"resourceProvider"`
}

func (Owner) IsEntity() {}

// Information about pagination in a connection.
// https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
type PageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue.
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue.
	EndCursor *string `json:"endCursor,omitempty"`
}

type ResourceProvider struct {
	// The ID of the resource provider.
	ID        gidx.PrefixedID `json:"id"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	// The name of the resource provider.
	Name string `json:"name"`
	// The description of the resource provider.
	Description *string `json:"description,omitempty"`
	// The owner of the resourceProvider.
	Owner Owner `json:"owner"`
}

func (ResourceProvider) IsNode() {}

// The id of the object.
func (this ResourceProvider) GetID() gidx.PrefixedID { return this.ID }

func (ResourceProvider) IsEntity() {}

// A connection to a list of items.
type ResourceProviderConnection struct {
	// A list of edges.
	Edges []*ResourceProviderEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	PageInfo PageInfo `json:"pageInfo"`
	// Identifies the total count of items in the connection.
	TotalCount int64 `json:"totalCount"`
}

// Return response from resourceProviderCreate
type ResourceProviderCreatePayload struct {
	// The created resource provider.
	ResourceProvider ResourceProvider `json:"resourceProvider"`
}

// Return response from resourceProviderDelete
type ResourceProviderDeletePayload struct {
	// The ID of the deleted resource provider.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// An edge in a connection.
type ResourceProviderEdge struct {
	// The item at the end of the edge.
	Node *ResourceProvider `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
}

// Ordering options for ResourceProvider connections
type ResourceProviderOrder struct {
	// The ordering direction.
	Direction OrderDirection `json:"direction"`
	// The field by which to order ResourceProviders.
	Field ResourceProviderOrderField `json:"field"`
}

// Return response from resourceProviderUpdate
type ResourceProviderUpdatePayload struct {
	// The updated resource provider.
	ResourceProvider ResourceProvider `json:"resourceProvider"`
}

// ResourceProviderWhereInput is used for filtering ResourceProvider objects.
// Input was generated by ent.
type ResourceProviderWhereInput struct {
	Not *ResourceProviderWhereInput   `json:"not,omitempty"`
	And []*ResourceProviderWhereInput `json:"and,omitempty"`
	Or  []*ResourceProviderWhereInput `json:"or,omitempty"`
	// id field predicates
	ID      *gidx.PrefixedID  `json:"id,omitempty"`
	IDNeq   *gidx.PrefixedID  `json:"idNEQ,omitempty"`
	IDIn    []gidx.PrefixedID `json:"idIn,omitempty"`
	IDNotIn []gidx.PrefixedID `json:"idNotIn,omitempty"`
	IDGt    *gidx.PrefixedID  `json:"idGT,omitempty"`
	IDGte   *gidx.PrefixedID  `json:"idGTE,omitempty"`
	IDLt    *gidx.PrefixedID  `json:"idLT,omitempty"`
	IDLte   *gidx.PrefixedID  `json:"idLTE,omitempty"`
	// created_at field predicates
	CreatedAt      *time.Time   `json:"createdAt,omitempty"`
	CreatedAtNeq   *time.Time   `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []*time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []*time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGt    *time.Time   `json:"createdAtGT,omitempty"`
	CreatedAtGte   *time.Time   `json:"createdAtGTE,omitempty"`
	CreatedAtLt    *time.Time   `json:"createdAtLT,omitempty"`
	CreatedAtLte   *time.Time   `json:"createdAtLTE,omitempty"`
	// updated_at field predicates
	UpdatedAt      *time.Time   `json:"updatedAt,omitempty"`
	UpdatedAtNeq   *time.Time   `json:"updatedAtNEQ,omitempty"`
	UpdatedAtIn    []*time.Time `json:"updatedAtIn,omitempty"`
	UpdatedAtNotIn []*time.Time `json:"updatedAtNotIn,omitempty"`
	UpdatedAtGt    *time.Time   `json:"updatedAtGT,omitempty"`
	UpdatedAtGte   *time.Time   `json:"updatedAtGTE,omitempty"`
	UpdatedAtLt    *time.Time   `json:"updatedAtLT,omitempty"`
	UpdatedAtLte   *time.Time   `json:"updatedAtLTE,omitempty"`
	// name field predicates
	Name             *string  `json:"name,omitempty"`
	NameNeq          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGt           *string  `json:"nameGT,omitempty"`
	NameGte          *string  `json:"nameGTE,omitempty"`
	NameLt           *string  `json:"nameLT,omitempty"`
	NameLte          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`
	// description field predicates
	Description             *string  `json:"description,omitempty"`
	DescriptionNeq          *string  `json:"descriptionNEQ,omitempty"`
	DescriptionIn           []string `json:"descriptionIn,omitempty"`
	DescriptionNotIn        []string `json:"descriptionNotIn,omitempty"`
	DescriptionGt           *string  `json:"descriptionGT,omitempty"`
	DescriptionGte          *string  `json:"descriptionGTE,omitempty"`
	DescriptionLt           *string  `json:"descriptionLT,omitempty"`
	DescriptionLte          *string  `json:"descriptionLTE,omitempty"`
	DescriptionContains     *string  `json:"descriptionContains,omitempty"`
	DescriptionHasPrefix    *string  `json:"descriptionHasPrefix,omitempty"`
	DescriptionHasSuffix    *string  `json:"descriptionHasSuffix,omitempty"`
	DescriptionIsNil        *bool    `json:"descriptionIsNil,omitempty"`
	DescriptionNotNil       *bool    `json:"descriptionNotNil,omitempty"`
	DescriptionEqualFold    *string  `json:"descriptionEqualFold,omitempty"`
	DescriptionContainsFold *string  `json:"descriptionContainsFold,omitempty"`
}

// Update an existing ResourceProvider.
type UpdateResourceProviderInput struct {
	// The name of the resource provider.
	Name *string `json:"name,omitempty"`
	// The description of the resource provider.
	Description      *string `json:"description,omitempty"`
	ClearDescription *bool   `json:"clearDescription,omitempty"`
}

type Service struct {
	Sdl *string `json:"sdl,omitempty"`
}

// Possible directions in which to order a list of items when provided an `orderBy` argument.
type OrderDirection string

const (
	// Specifies an ascending order for a given `orderBy` argument.
	OrderDirectionAsc OrderDirection = "ASC"
	// Specifies a descending order for a given `orderBy` argument.
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Properties by which ResourceProvider connections can be ordered.
type ResourceProviderOrderField string

const (
	ResourceProviderOrderFieldID          ResourceProviderOrderField = "ID"
	ResourceProviderOrderFieldCreatedAt   ResourceProviderOrderField = "CREATED_AT"
	ResourceProviderOrderFieldUpdatedAt   ResourceProviderOrderField = "UPDATED_AT"
	ResourceProviderOrderFieldName        ResourceProviderOrderField = "NAME"
	ResourceProviderOrderFieldDescription ResourceProviderOrderField = "DESCRIPTION"
)

var AllResourceProviderOrderField = []ResourceProviderOrderField{
	ResourceProviderOrderFieldID,
	ResourceProviderOrderFieldCreatedAt,
	ResourceProviderOrderFieldUpdatedAt,
	ResourceProviderOrderFieldName,
	ResourceProviderOrderFieldDescription,
}

func (e ResourceProviderOrderField) IsValid() bool {
	switch e {
	case ResourceProviderOrderFieldID, ResourceProviderOrderFieldCreatedAt, ResourceProviderOrderFieldUpdatedAt, ResourceProviderOrderFieldName, ResourceProviderOrderFieldDescription:
		return true
	}
	return false
}

func (e ResourceProviderOrderField) String() string {
	return string(e)
}

func (e *ResourceProviderOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceProviderOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceProviderOrderField", str)
	}
	return nil
}

func (e ResourceProviderOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
