// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"go.infratographer.com/resource-provider-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

type OrganizationalUnit struct {
	ID               gidx.PrefixedID                       `json:"id"`
	ResourceProvider *generated.ResourceProviderConnection `json:"resourceProvider"`
}

func (OrganizationalUnit) IsEntity() {}

// Return response from resourceProviderCreate
type ResourceProviderCreatePayload struct {
	// The created resource provider.
	ResourceProvider *generated.ResourceProvider `json:"resourceProvider"`
}

// Return response from resourceProviderDelete
type ResourceProviderDeletePayload struct {
	// The ID of the deleted resource provider.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from resourceProviderUpdate
type ResourceProviderUpdatePayload struct {
	// The updated resource provider.
	ResourceProvider *generated.ResourceProvider `json:"resourceProvider"`
}
