package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/resource-provider-api/internal/ent/generated"
	"go.infratographer.com/resource-provider-api/internal/ent/generated/resourceprovider"
	"go.infratographer.com/x/gidx"
)

// ResourceProvider is the resolver for the resourceProvider field.
func (r *ownerResolver) ResourceProvider(ctx context.Context, obj *Owner, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.ResourceProviderOrder, where *generated.ResourceProviderWhereInput) (*generated.ResourceProviderConnection, error) {
	return r.client.ResourceProvider.Query().
		Where(
			resourceprovider.OwnerID(obj.ID),
		).Paginate(
		ctx,
		after,
		first,
		before,
		last,
		generated.WithResourceProviderOrder(orderBy),
		generated.WithResourceProviderFilter(where.Filter),
	)
}

// Owner is the resolver for the owner field.
func (r *resourceProviderResolver) Owner(ctx context.Context, obj *generated.ResourceProvider) (*Owner, error) {
	return &Owner{ID: obj.OwnerID}, nil
}

// Owner returns OwnerResolver implementation.
func (r *Resolver) Owner() OwnerResolver { return &ownerResolver{r} }

type ownerResolver struct{ *Resolver }
